version: "3.8"
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./:/var/www/html # Mount full project for theme/plugin/core access
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Persist MySQL data
  wpcli:
    image: wordpress:cli
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./:/var/www/html # Mount full project for WP-CLI automation
      - db_data:/var/lib/mysql # Access to DB data
    entrypoint: ["sleep", "infinity"] # Keep container running for exec

# Named volume for MySQL data persistence
volumes:
  db_data:
    # MySQL data volume
