name: CI

on:
  push:
    branches: [main, develop, 'feature/*', 'bugfix/*']
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: PHP Lint
        run: find . -name '*.php' -exec php -l {} \;
      - name: JS Lint
        run: |
          if [ -f package.json ]; then npm install && npm run lint || true; fi
      - name: CSS Lint
        run: |
          if [ -f package.json ]; then npm run stylelint || true; fi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Composer dependencies
        run: |
          if [ -f composer.json ]; then composer install; fi
      - name: Run PHPUnit
        run: |
          if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit; fi 